mysql:
  username: ''
  password: ''
  host: localhost
  database: bukkit
  port: 3306
  prefix: ''
  savesPerDay: 64
BastionBlock:
  material: SPONGE
  effectRadius: 10
  startScaleFactor: 100
  finalScaleFactor: 0.2
  warmUpTime: 86400000
  maxBreaksPerMinute: 30
  erosionRatePerDay: 0
  destroyOnRemove: false
  EnderPearls:
    preventEnderPearl: true 
    scaleFac: 1
    requireMaturity: true 
  
