name: Bastion
version: 0.6.0
main: isaac.bastion.Bastion
depend: [Citadel]
softdepend: [Humbug]
commands:
   Bastion:
      description: Base command for Bastion
      usage: /Bastion <About or License>
      permission: Bastion.normal
   bsi:
      description: Gives info on blocks that are clicked
      usage: /bsi and right click a block
      permission: Bastion.normal
   bsd:
      description: Removes Bastion Block when clicked
      usage: /bsd and right click a block
      permission: Bastion.normal
   bso:
      description: Returns to normal
      usage: /bso set the mode back to normal
      permission: Bastion.normal
   bsc:
      description: Turns mode to Bastion creation mode
      usage: /bsc set the mode back to create. Any times a target block is reinforced it will become a Bastion 
      permission: Bastion.normal
   bsb:
      description: Turns mode to Bastion mode
      usage: /bsc set the mode back to bastion when clicking a reinforced target block it becomes a Bastion 
      permission: Bastion.normal
   bsm:
      description: Insta matures any bastion left clicked 
      usage: /bsm
      permission: Bastion.admin
permissions:
    Bastion.*:
        description: Gives access to all Bastion commands
        default: op
    Bastion.normal:
        description: All a normal player should ever need
        default: true
    Bastion.admin:
        description: Special power for admins
        default: op
        children:
            Bastion.bypass: true
    Bastion.bypass:
        description: Bastions do not effect members
        default: false
    Bastion.dev:
        description: Special debug commands and different responses to existing commands
        default: op